/*
------------------------------------------------
Generated by Cradle 2.0.0.0 on 10/05/2016 11:41:42
https://github.com/daterre/Cradle

Original file: eachword.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @eachword: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@eachword()
	{
		this.StartPassage = "clickable";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
	}
	
	void Awake() {
		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: clickable

	void passage1_Init()
	{
		this.Passages[@"clickable"] = new StoryPassage(@"clickable", new string[]{  }, passage1_Main);
	}

	#line 1 "clickable"
	IStoryThread passage1_Main()
	{
		yield return link("each", "each", null);
		yield return text(" ");
		yield return link("word", "word", null);
		yield return text(" ");
		yield return link("is", "is", null);
		yield return text(" ");
		yield return link("clickable", "clickable", null);
		yield break;
	}


	// .............
	// #2: each

	void passage2_Init()
	{
		this.Passages[@"each"] = new StoryPassage(@"each", new string[]{  }, passage2_Main);
	}

	#line 1 "each"
	IStoryThread passage2_Main()
	{
		yield return link("each", "each", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield return text(" ");
		yield return link("will", "will", null);
		yield return text(" ");
		yield return link("lead", "lead", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #3: word

	void passage3_Init()
	{
		this.Passages[@"word"] = new StoryPassage(@"word", new string[]{  }, passage3_Main);
	}

	#line 1 "word"
	IStoryThread passage3_Main()
	{
		yield return link("word", "word", null);
		yield return text(", ");
		yield return link("words", "words", null);
		yield return text(". ");
		yield return link("each", "each", null);
		yield return text(" ");
		yield return link("lead", "lead", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield break;
	}


	// .............
	// #4: is

	void passage4_Init()
	{
		this.Passages[@"is"] = new StoryPassage(@"is", new string[]{  }, passage4_Main);
	}

	#line 1 "is"
	IStoryThread passage4_Main()
	{
		yield return link("is", "is", null);
		yield return text(" ");
		yield return link("it", "it", null);
		yield return text(" ");
		yield return link("a", "a", null);
		yield return text(" ");
		yield return link("question", "question", null);
		yield break;
	}


	// .............
	// #5: click

	void passage5_Init()
	{
		this.Passages[@"click"] = new StoryPassage(@"click", new string[]{  }, passage5_Main);
	}

	#line 1 "click"
	IStoryThread passage5_Main()
	{
		yield return link("click", "click", null);
		yield return text(" ");
		yield return link("on", "on", null);
		yield return text(" ");
		yield return link("it", "it", null);
		yield return text(", ");
		yield return link("then", "then", null);
		yield break;
	}


	// .............
	// #6: will

	void passage6_Init()
	{
		this.Passages[@"will"] = new StoryPassage(@"will", new string[]{  }, passage6_Main);
	}

	#line 1 "will"
	IStoryThread passage6_Main()
	{
		yield return link("will", "will", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield return text(" ");
		yield return link("on", "on", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield break;
	}


	// .............
	// #7: lead

	void passage7_Init()
	{
		this.Passages[@"lead"] = new StoryPassage(@"lead", new string[]{  }, passage7_Main);
	}

	#line 1 "lead"
	IStoryThread passage7_Main()
	{
		yield return link("lead", "lead", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield return text(" ");
		yield return link("of", "of", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #8: to

	void passage8_Init()
	{
		this.Passages[@"to"] = new StoryPassage(@"to", new string[]{  }, passage8_Main);
	}

	#line 1 "to"
	IStoryThread passage8_Main()
	{
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("each", "each", null);
		yield return text(" ");
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("will", "will", null);
		yield return text(" ");
		yield return link("then", "then", null);
		yield return text(" ");
		yield return link("say", "say", null);
		yield break;
	}


	// .............
	// #9: words

	void passage9_Init()
	{
		this.Passages[@"words"] = new StoryPassage(@"words", new string[]{  }, passage9_Main);
	}

	#line 1 "words"
	IStoryThread passage9_Main()
	{
		yield return link("words", "words", null);
		yield return text(", ");
		yield return link("oh", "oh", null);
		yield return text(", ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #10: places

	void passage10_Init()
	{
		this.Passages[@"places"] = new StoryPassage(@"places", new string[]{  }, passage10_Main);
	}

	#line 1 "places"
	IStoryThread passage10_Main()
	{
		yield return link("places", "places", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("a", "a", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield break;
	}


	// .............
	// #11: oh

	void passage11_Init()
	{
		this.Passages[@"oh"] = new StoryPassage(@"oh", new string[]{  }, passage11_Main);
	}

	#line 1 "oh"
	IStoryThread passage11_Main()
	{
		yield return link("oh", "oh", null);
		yield return text(", ");
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("say", "say", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield return text(" ");
		yield return link("are", "are", null);
		yield break;
	}


	// .............
	// #12: the

	void passage12_Init()
	{
		this.Passages[@"the"] = new StoryPassage(@"the", new string[]{  }, passage12_Main);
	}

	#line 1 "the"
	IStoryThread passage12_Main()
	{
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield return text(" ");
		yield return link("are", "are", null);
		yield return text(" ");
		yield return link("all", "all", null);
		yield return text(" ");
		yield return link("a", "a", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield break;
	}


	// .............
	// #13: it

	void passage13_Init()
	{
		this.Passages[@"it"] = new StoryPassage(@"it", new string[]{  }, passage13_Main);
	}

	#line 1 "it"
	IStoryThread passage13_Main()
	{
		yield return link("it", "it", null);
		yield return text(" ");
		yield return link("is", "is", null);
		yield return text(" ");
		yield return link("each", "each", null);
		yield return text(" ");
		yield return link("word", "word", null);
		yield break;
	}


	// .............
	// #14: a

	void passage14_Init()
	{
		this.Passages[@"a"] = new StoryPassage(@"a", new string[]{  }, passage14_Main);
	}

	#line 1 "a"
	IStoryThread passage14_Main()
	{
		yield return link("a", "a", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield return text(" ");
		yield return link("away", "away", null);
		yield break;
	}


	// .............
	// #15: question

	void passage15_Init()
	{
		this.Passages[@"question"] = new StoryPassage(@"question", new string[]{  }, passage15_Main);
	}

	#line 1 "question"
	IStoryThread passage15_Main()
	{
		yield return link("a", "a", null);
		yield return text(" ");
		yield return link("question", "question", null);
		yield return text(" ");
		yield return link("of", "of", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield break;
	}


	// .............
	// #16: of

	void passage16_Init()
	{
		this.Passages[@"of"] = new StoryPassage(@"of", new string[]{  }, passage16_Main);
	}

	#line 1 "of"
	IStoryThread passage16_Main()
	{
		yield return link("of", "of", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield return text(" ");
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("say", "say", null);
		yield break;
	}


	// .............
	// #17: away

	void passage17_Init()
	{
		this.Passages[@"away"] = new StoryPassage(@"away", new string[]{  }, passage17_Main);
	}

	#line 1 "away"
	IStoryThread passage17_Main()
	{
		yield return link("away", "away", null);
		yield break;
	}


	// .............
	// #18: they

	void passage18_Init()
	{
		this.Passages[@"they"] = new StoryPassage(@"they", new string[]{  }, passage18_Main);
	}

	#line 1 "they"
	IStoryThread passage18_Main()
	{
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield return text(" ");
		yield return link("on", "on", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #19: say

	void passage19_Init()
	{
		this.Passages[@"say"] = new StoryPassage(@"say", new string[]{  }, passage19_Main);
	}

	#line 1 "say"
	IStoryThread passage19_Main()
	{
		yield return link("say", "say", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("word", "word", null);
		yield return text(", ");
		yield return link("and", "and", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield break;
	}


	// .............
	// #20: on

	void passage20_Init()
	{
		this.Passages[@"on"] = new StoryPassage(@"on", new string[]{  }, passage20_Main);
	}

	#line 1 "on"
	IStoryThread passage20_Main()
	{
		yield return link("on", "on", null);
		yield return text(" ");
		yield return link("all", "all", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #21: all

	void passage21_Init()
	{
		this.Passages[@"all"] = new StoryPassage(@"all", new string[]{  }, passage21_Main);
	}

	#line 1 "all"
	IStoryThread passage21_Main()
	{
		yield return link("all", "all", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield return text(", ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield return text(", ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("clickable", "clickable", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield break;
	}


	// .............
	// #22: and

	void passage22_Init()
	{
		this.Passages[@"and"] = new StoryPassage(@"and", new string[]{  }, passage22_Main);
	}

	#line 1 "and"
	IStoryThread passage22_Main()
	{
		yield return link("and", "and", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield return text(" ");
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("all", "all", null);
		yield break;
	}


	// .............
	// #23: are

	void passage23_Init()
	{
		this.Passages[@"are"] = new StoryPassage(@"are", new string[]{  }, passage23_Main);
	}

	#line 1 "are"
	IStoryThread passage23_Main()
	{
		yield return link("are", "are", null);
		yield return text(" ");
		yield return link("all", "all", null);
		yield return text(" ");
		yield return link("the", "the", null);
		yield return text(" ");
		yield return link("words", "words", null);
		yield return text(" ");
		yield return link("taken", "taken", null);
		yield break;
	}


	// .............
	// #24: then

	void passage24_Init()
	{
		this.Passages[@"then"] = new StoryPassage(@"then", new string[]{  }, passage24_Main);
	}

	#line 1 "then"
	IStoryThread passage24_Main()
	{
		yield return link("then", "then", null);
		yield return text(" ");
		yield return link("they", "they", null);
		yield return text(" ");
		yield return link("will", "will", null);
		yield return text(" ");
		yield return link("click", "click", null);
		yield break;
	}


	// .............
	// #25: taken

	void passage25_Init()
	{
		this.Passages[@"taken"] = new StoryPassage(@"taken", new string[]{  }, passage25_Main);
	}

	#line 1 "taken"
	IStoryThread passage25_Main()
	{
		yield return link("taken", "taken", null);
		yield return text(" ");
		yield return link("away", "away", null);
		yield return text(" ");
		yield return link("to", "to", null);
		yield return text(" ");
		yield return link("places", "places", null);
		yield break;
	}


}